import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
export async function startFixture(){
 const tokens=new Set<string>();const files=new Map<string,string>();
 const css=`body{background:#100c18;color:#e7d8f4;font:15px system-ui;max-width:820px;margin:60px auto;padding:30px}h1{font-size:38px;color:#b287e9}label{display:block;margin:18px 0}input,textarea,button,select{font:inherit;padding:12px;background:#21152e;border:1px solid #794996;color:#f5e9ff}textarea{display:block;width:90%;height:80px}button,a{cursor:pointer;color:#ff5bb7}section{border:1px solid #4c305e;padding:25px;margin-top:25px}small{color:#b598c8}#status{padding:20px 0}a{display:inline-block;margin-right:15px}`;
 const doc=(body:string)=>`<!doctype html><html lang="ko"><meta charset="utf-8"><title>HONMOON Test Lab</title><style>${css}</style>${body}</html>`;
 const server=createServer((req,res)=>{const url=new URL(req.url||'/','http://localhost');const token=/hm_session=([^;]+)/.exec(req.headers.cookie||'')?.[1];const logged=token&&tokens.has(token);
  if(url.pathname==='/login'&&req.method==='POST'){const t=randomUUID();tokens.add(t);res.writeHead(200,{'Set-Cookie':`hm_session=${t}; HttpOnly; SameSite=Strict; Path=/`,'Content-Type':'application/json'}).end('{}');return;}
  if(url.pathname==='/logout'){if(token)tokens.delete(token);res.writeHead(302,{'Set-Cookie':'hm_session=; Max-Age=0; Path=/','Location':'/'}).end();return;}
  if(url.pathname==='/upload'&&req.method==='POST'){if(!logged){res.writeHead(401).end();return;}let bytes=0;req.on('data',b=>{bytes+=b.length;if(bytes>100*1024*1024)req.destroy();});req.on('end',()=>res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({bytes})));return;}
  if(url.pathname==='/generate'&&req.method==='POST'){if(!logged){res.writeHead(401).end();return;}const id=randomUUID();files.set(id,`<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540"><rect width="960" height="540" fill="#100c18"/><circle cx="480" cy="240" r="130" fill="none" stroke="#a878ed" stroke-width="16"/><path d="m420 220 60 60 60-60" fill="none" stroke="#ff39ad" stroke-width="16"/><text x="480" y="450" text-anchor="middle" fill="#eee6f6" font-size="30" font-family="sans-serif">HONMOON LOCAL TEST ARTIFACT</text></svg>`);res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({id}));return;}
  if(url.pathname.startsWith('/download/')){if(!logged){res.writeHead(401).end();return;}const svg=files.get(url.pathname.split('/').pop()!);if(!svg){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':'image/svg+xml','Content-Disposition':'attachment; filename="honmoon-test.svg"'}).end(svg);return;}
  res.setHeader('Content-Type','text/html; charset=utf-8');
  if(url.pathname==='/newtab'){res.end(`<!doctype html><html lang="ko"><meta charset="utf-8"><title>새 탭</title><style>body{margin:0;background:#111015;color:#ddd;font:15px system-ui;height:100vh;display:grid;place-items:center}form{display:flex;width:min(520px,80vw);border:1px solid #39323f;border-radius:24px;overflow:hidden;background:#1c1921}input{flex:1;min-width:0;background:none;border:0;padding:15px 22px;color:#eee;font:inherit;outline:none}button{border:0;background:none;color:#bc9add;padding:0 22px;font:inherit;cursor:pointer}</style><form action="https://www.google.com/search"><input name="q" aria-label="웹 검색" placeholder="웹 검색" autocomplete="off"><button>검색</button></form></html>`);return;}
  if(!logged){res.end(doc(`<small>LOCAL TEST SITE · 실제 서비스가 아닙니다</small><h1>HONMOON Test Lab</h1><p>내장 Chromium의 로그인·입력·업로드·다운로드를 검증하는 로컬 사이트입니다.</p><section><h2>테스트 로그인</h2><label>테스트 이름 <input aria-label="테스트 이름" autocomplete="off"></label><button id="login">테스트 로그인</button><p>실제 이메일·비밀번호를 입력하지 마세요.</p></section><script>document.querySelector('#login').onclick=async()=>{await fetch('/login',{method:'POST'});location.href='/workspace'}</script>`));return;}
  res.end(doc(`<small>LOCAL TEST SITE · 실제 AI 생성이나 과금 없음</small><h1>테스트 작업 공간</h1><p>로그인 세션이 활성화되었습니다.</p><a href="/logout">로그아웃</a><a href="/workspace?spa=1" id="spa">SPA 이동 테스트</a><section><h2>산출물 만들기</h2><label>프롬프트<textarea aria-label="프롬프트" id="prompt"></textarea></label><label>화면 비율<select aria-label="화면 비율"><option>16:9</option><option>1:1</option></select></label><label>참조 파일<input type="file" aria-label="참조 파일" id="file"></label><div id="upload-status">선택된 파일 없음</div><button id="generate">테스트 산출물 생성</button><div id="status" role="status">준비 완료</div><div id="result"></div></section><script>document.querySelector('#spa').onclick=e=>{e.preventDefault();history.pushState({},'', '/workspace?spa=1');document.querySelector('h1').textContent='SPA 작업 공간'};document.querySelector('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;const data=new FormData();data.append('file',f);await fetch('/upload',{method:'POST',body:data});document.querySelector('#upload-status').textContent='업로드 완료: '+f.name};document.querySelector('#generate').onclick=async()=>{document.querySelector('#status').textContent='처리 중';const r=await(await fetch('/generate',{method:'POST'})).json();document.querySelector('#status').textContent='테스트 생성 완료';document.querySelector('#result').replaceChildren(Object.assign(document.createElement('a'),{href:'/download/'+r.id,textContent:'결과 다운로드'}))};</script>`));
 });await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));return {server,url:`http://127.0.0.1:${(server.address() as any).port}`};
}
