import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,existsSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {normalizeUrl} from './browser.js';
export async function verify(ctx:any){
 const {browser,adapter,core,permissions,store,fixtureUrl,root,window}=ctx;const results:any[]=[];const start=Date.now();
 const pass=(name:string,data?:any)=>{results.push({name,passed:true,...data});console.log('PASS',name);};
 const eventually=async(fn:()=>boolean|Promise<boolean>,ms=10000)=>{const end=Date.now()+ms;while(Date.now()<end){if(await fn())return;await browser.wait(100);}throw new Error('Condition timed out');};
 const approve=async(promise:Promise<any>,allow=true)=>{await eventually(()=>permissions.list().length>0);permissions.decide(permissions.list()[0].id,allow);return promise;};
 const first=browser.activeId();window.show();const wc=browser.views.get(first).view.webContents;wc.focus();await browser.wait(1000);const target=await browser.target(first);mkdirSync(join(root,'evidence'),{recursive:true});writeFileSync(join(root,'evidence','before.png'),(await window.capturePage()).toPNG());
 await wc.executeJavaScript("window.__clicks=[];document.addEventListener('click',e=>window.__clicks.push({x:e.clientX,y:e.clientY,target:e.target.tagName,id:e.target.id}),true)");await adapter.target(target,(c:any)=>c(['click','#login']));try{await eventually(()=>browser.tab(first).url.endsWith('/workspace'));}catch(e){console.log('LOGIN DIAGNOSTIC',await wc.executeJavaScript('JSON.stringify({clicks:window.__clicks,rect:document.querySelector("#login").getBoundingClientRect().toJSON(),width:innerWidth,height:innerHeight,scale:devicePixelRatio})'),browser.bounds,window.isMinimized());console.log('VIEWS',window.contentView.children.map((v:any)=>({id:v.webContents?.id,url:v.webContents?.getURL(),bounds:v.getBounds(),visible:v.getVisible()})));throw e;}
 await eventually(async()=>await wc.executeJavaScript("getComputedStyle(document.documentElement,'::-webkit-scrollbar-thumb').backgroundColor==='rgb(128, 96, 149)'"));pass('Local site login through embedded Chromium with default themed scrollbars');
 const shellLayout=await window.webContents.executeJavaScript(`(()=>{const r=document.querySelector('.tabbar').getBoundingClientRect();const overlay=navigator.windowControlsOverlay;return {top:r.top,right:r.right,area:overlay.getTitlebarAreaRect().toJSON(),overlay:overlay.visible,hasLogo:!!document.querySelector('.wordmark,.rail')};})()`);assert.equal(shellLayout.overlay,true);assert.equal(shellLayout.hasLogo,false);assert.equal(shellLayout.top,0);assert.ok(shellLayout.right<=shellLayout.area.x+shellLayout.area.width+1);const narrow=browser.bounds.width;await window.webContents.executeJavaScript(`document.querySelector('.agent-toggle').click()`);await eventually(()=>browser.bounds.width>narrow);await window.webContents.executeJavaScript(`document.querySelector('.agent-toggle').click()`);await eventually(()=>browser.bounds.width===narrow);pass('Integrated titlebar safe area and collapsible browser workspace');
 for(let i=0;i<20;i++){
  const tab=await browser.create(fixtureUrl+'/workspace?cycle='+i);const twc=browser.views.get(tab.id).view.webContents;await twc.executeJavaScript("window.__clicks=[];document.addEventListener('click',e=>window.__clicks.push({x:e.clientX,y:e.clientY,target:e.target.tagName,id:e.target.id}),true)");if(i===7)window.minimize();const tid=await browser.target(tab.id);assert.equal(window.isMinimized(),false);const result=await adapter.target(tid,(c:any)=>c(['snapshot','-i','-c']));assert.match(result.snapshot,/프롬프트/);assert.equal(new URL(result.origin).origin,new URL(fixtureUrl).origin);await adapter.target(tid,(c:any)=>c(['click','#generate']));try{await eventually(async()=>/테스트 생성 완료/.test(await twc.executeJavaScript('document.querySelector("#status").textContent')));}catch(e){console.log('CLICK DIAGNOSTIC',await twc.executeJavaScript('JSON.stringify({clicks:window.__clicks,rect:document.querySelector("#generate").getBoundingClientRect().toJSON(),viewport:{w:innerWidth,h:innerHeight,scale:devicePixelRatio,offset:visualViewport.offsetTop},scrollY})'),browser.bounds);throw e;}browser.close(tab.id);await assert.rejects(()=>adapter.target(tid,(c:any)=>c(['snapshot'])),/대상 탭|STALE/);if((i+1)%5===0)console.log('TAB CYCLES',i+1);
 }browser.activate(first);pass('20 native tab create / target / snapshot / close cycles');
 const second=await browser.create(fixtureUrl+'/workspace');await core.list(second.id);const wrong=core.capabilities[0];browser.activate(first);await core.start('Wrong live tab',first,undefined,true);await assert.rejects(core.invoke({id:wrong.id,input:{},requestId:'wrong-tab'}),/현재 작업 탭/);pass('Capabilities from a different live tab rejected');
 const recoveryTask=core.task.id;await assert.rejects(core.tool('page.inspect',{level:'screenshot'},recoveryTask),/순서/);const ax=await approve(core.tool('page.inspect',{level:'accessibility'},recoveryTask));assert.ok(ax.elements.length);const dom=await approve(core.tool('page.inspect',{level:'dom'},recoveryTask));assert.match(dom.dom,/TEXTAREA/);const shot=await approve(core.tool('page.inspect',{level:'screenshot'},recoveryTask));assert.ok(Buffer.from(shot.imageData,'base64').length>1000);core.cancel();browser.close(second.id);pass('Consent-gated accessibility / limited DOM / screenshot recovery');
 const caps=await core.list(first);const fill=caps.find((c:any)=>c.name==='프롬프트'&&c.action==='fill');assert.ok(fill);
 const aliasTask=await core.start('Test approved fill',first,undefined,true);const found=await core.tool('capabilities.find',{query:'프롬프트',action:'fill'},aliasTask.id);assert.equal(found.candidates.length,1);const inspected=await core.tool('capabilities.inspect',{id:found.candidates[0].id},aliasTask.id);assert.equal(inspected.ambiguous,false);assert.deepEqual(inspected.inputSchema.required,['value']);const presented=await core.tool('capabilities.list',{},aliasTask.id);const alias=presented.capabilities.find((c:any)=>c.name==='프롬프트'&&c.action==='fill').id;assert.match(alias,/^c\d+$/);const repeated=await core.tool('capabilities.list',{},aliasTask.id);assert.equal(repeated.unchanged,true);const invoke={id:alias,input:{value:'HONMOON 실제 입력 검증'},requestId:'fill-once'};
 const result=await approve(core.invoke(invoke));assert.equal(result.execution,'acknowledged');assert.equal(await wc.executeJavaScript('document.querySelector("#prompt").value'),'HONMOON 실제 입력 검증');assert.deepEqual(await core.invoke(invoke),result);pass('Compact capability alias executes approved input + idempotency');core.finish('succeeded');
 await core.list(first);await core.start('Denied action',first,undefined,true);const denied=core.invoke({id:core.capabilities.find((c:any)=>c.name==='프롬프트').id,input:{value:'SHOULD_NOT_APPEAR'},requestId:'denied'});const denial=assert.rejects(()=>approve(denied,false),/승인/);await denial;assert.notEqual(await wc.executeJavaScript('document.querySelector("#prompt").value'),'SHOULD_NOT_APPEAR');core.cancel();pass('Approval denial prevents mutation');
 await core.list(first);await core.start('Cancel pending',first,undefined,true);const cancelPromise=core.invoke({id:core.capabilities.find((c:any)=>c.name==='프롬프트').id,input:{value:'CANCELLED'},requestId:'cancel'});const cancelled=assert.rejects(cancelPromise,/취소/);await eventually(()=>permissions.list().length>0);const cancelledDaemon=adapter.daemonPid();assert.ok(cancelledDaemon);core.cancel();await cancelled;await eventually(()=>{try{process.kill(cancelledDaemon,0);return false;}catch{return true;}});assert.notEqual(await wc.executeJavaScript('document.querySelector("#prompt").value'),'CANCELLED');pass('Cancel terminates automation daemon and prevents queued continuation');
 await core.list(first);await core.start('Stale target',first,undefined,true);const stale=core.invoke({id:core.capabilities.find((c:any)=>c.name==='프롬프트').id,input:{value:'STALE'},requestId:'stale'});const rejected=assert.rejects(stale,/변경/);await eventually(()=>permissions.list().length>0);await wc.executeJavaScript("history.pushState({},'', '/workspace?changed=1')");permissions.decide(permissions.list()[0].id,true);await rejected;core.cancel();pass('Navigation invalidates approval');
 await core.list(first);await core.start('Wrong file',first,undefined,true);const upload=core.capabilities.find((c:any)=>c.action==='upload');assert.ok(upload);await assert.rejects(core.invoke({id:upload.id,input:{fileId:'unapproved'},requestId:'bad-file'}),/파일 ID/);core.cancel();pass('Unselected file denied');
 const path=join(root,'evidence','upload-fixture.txt');mkdirSync(join(root,'evidence'),{recursive:true});writeFileSync(path,'HONMOON upload evidence');const file=core.addFile(path);await core.list(first);await core.start('Upload',first,undefined,true);await approve(core.invoke({id:core.capabilities.find((c:any)=>c.action==='upload').id,input:{fileId:file.id},requestId:'upload'}));await eventually(async()=>/업로드 완료/.test(await wc.executeJavaScript('document.querySelector("#upload-status").textContent')));core.finish('succeeded');pass('Approved real file upload');
 await core.list(first);await core.start('Generate and download fixture',first,undefined,true);await approve(core.invoke({id:core.capabilities.find((c:any)=>c.name==='테스트 산출물 생성').id,input:{},requestId:'generate'}));await eventually(async()=>/테스트 생성 완료/.test(await wc.executeJavaScript('document.querySelector("#status").textContent')));await core.list(first);await approve(core.invoke({id:core.capabilities.find((c:any)=>c.name==='결과 다운로드').id,input:{},requestId:'download'}));await eventually(()=>store.artifacts().some((a:any)=>a.status==='completed'));const artifact=store.artifacts()[0];assert.ok(existsSync(artifact.path));assert.match(readFileSync(artifact.path,'utf8'),/HONMOON LOCAL TEST ARTIFACT/);core.finish('succeeded');pass('Actual download and artifact provenance',{bytes:artifact.bytes});
 browser.tab(first).authPaused=true;await assert.rejects(core.list(first),/인증/);browser.tab(first).authPaused=false;await wc.executeJavaScript("{const p=document.createElement('input');p.type='password';p.id='secret-field';p.value='DO_NOT_EXPOSE';document.body.append(p)}");await assert.rejects(core.list(first),/인증/);await wc.executeJavaScript("document.querySelector('#secret-field').remove()");pass('Manual and detected authentication shielding');
 await core.start('Lease exclusivity',first,undefined,true);await assert.rejects(core.start('Second task',first,undefined,true),/이미/);core.cancel();pass('Profile-exclusive lease');
 await core.start('Lease timeout',first,undefined,true);core.task.expiresAt=Date.now()-1;await eventually(()=>!core.task);assert.equal(store.tasks()[0].error,'LEASE_EXPIRED');pass('Expired lease stops task');
 await core.start('Physical handoff',first,undefined,true);const guard=window.contentView.children.find((v:any)=>/^data:text\/html(?:;charset=utf-8)?,/.test(v.webContents?.getURL()||''));assert.ok(guard);guard.webContents.sendInputEvent({type:'mouseDown',x:20,y:20,button:'left',clickCount:1});guard.webContents.sendInputEvent({type:'mouseUp',x:20,y:20,button:'left',clickCount:1});await eventually(()=>!core.task);assert.equal(store.tasks()[0].error,'USER_HANDOFF');pass('Native input shield hands control back to human');
 assert.throws(()=>normalizeUrl('javascript:alert(1)'));assert.throws(()=>normalizeUrl('file:///C:/Windows/win.ini'));assert.throws(()=>normalizeUrl('https://user:pass@example.com'));pass('Dangerous navigation schemes denied');
 assert.equal(await wc.executeJavaScript('typeof require'),'undefined');assert.equal(await wc.executeJavaScript('typeof window.honmoon'),'undefined');pass('Website has no Node or product IPC');
 await assert.rejects(core.tool('approvals.decide',{allow:true}),/권한|허용/);await assert.rejects(core.tool('approvals.task',{allow:true}),/권한|허용/);pass('Agent cannot grant approval');
 const whole=await core.start('Local fixture whole-task approval',first,undefined,true);await browser.wait(200);await window.webContents.executeJavaScript(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent==='이 작업 전체 승인');if(!b)throw Error('Missing whole-task approval button');b.click();})()`);await eventually(async()=>await window.webContents.executeJavaScript(`!!document.querySelector('[aria-label="전체 승인 생성 횟수"]')`));assert.match(await window.webContents.executeJavaScript(`document.querySelector('[role="dialog"]').textContent`),/Local fixture whole-task approval/);await window.webContents.executeJavaScript(`(()=>{const buttons=[...document.querySelector('[role="dialog"]').querySelectorAll('button')];buttons.find(b=>b.textContent==='이 작업 전체 승인').click();})()`);await eventually(()=>!!permissions.taskGrant(whole.id));assert.equal(permissions.taskGrant(whole.id).allowUnknownCost,false);const wcaps=await core.list(first);await core.invoke({id:wcaps.find((c:any)=>c.name==='프롬프트'&&c.action==='fill').id,input:{value:'WHOLE TASK APPROVED'},requestId:'whole-approved'});assert.equal(permissions.list().length,0);assert.equal(await wc.executeJavaScript('document.querySelector("#prompt").value'),'WHOLE TASK APPROVED');core.cancel();assert.equal(permissions.taskGrant(whole.id),undefined);pass('Whole-task UI approval executes local input without repeat prompts and revokes on cancel');
 await core.start('Result requires review',first,undefined,true);await approve(core.reviewCompletion('브라우저 명령만 완료됨'),false);assert.equal(store.tasks()[0].status,'failed');pass('Agent response completion does not self-certify business success');
 await ctx.codex.connect();assert.equal(ctx.codex.status,'ready');assert.ok(ctx.codex.models.length);pass('Real Codex app-server initializes and lists models',{authenticated:!!ctx.codex.account,models:ctx.codex.models.length});
 await browser.wait(1000);const image=await window.capturePage();writeFileSync(join(root,'evidence','desktop.png'),image.toPNG());
 const report={at:new Date().toISOString(),durationMs:Date.now()-start,versions:ctx.state().versions,results,limitations:['Flow/Grok authenticated pilot pending','Codex device login requires user participation','No remote Chrome used']};writeFileSync(join(root,'evidence','verification.json'),JSON.stringify(report,null,2));console.log('VERIFICATION COMPLETE',results.length);
}
