import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {join,resolve,dirname,basename} from 'node:path';
import {tmpdir} from 'node:os';
import {Store} from '../packages/core/store.js';
import {Orchestrator} from '../packages/core/orchestrator.js';
import {CodexAdapter} from '../packages/codex-adapter/index.js';
import {mediaSchema,mediaSite,type MediaPage,type MediaControl} from '../packages/core/media-contract.js';
import {isImage,isVideo,normalizePrompt} from '../packages/core/media-runner.js';
import {executeToolSchema,executeSchema} from '../packages/core/browser-contract.js';
import {Permissions} from '../packages/core/permissions.js';

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jp1sAAAAASUVORK5CYII=','base64');
const c=(key:string,name:string,role='button',checked=false):MediaControl=>({key,selector:'#'+key,name,role,scope:'',value:'',checked,disabled:false,hidden:false});
async function harness(mutate?:(kind:string,p:MediaPage,core:Orchestrator)=>boolean){
 const dir=mkdtempSync(join(tmpdir(),'honmoon-media-'));const store=new Store(join(dir,'db.sqlite'));let active='tab',auth=false,submits=0;
 const page:MediaPage={site:'flow',version:'2026-09-28.1',url:'https://flow.google.com/project/test',editor:{...c('editor','프롬프트','textbox'),value:''},controls:[c('settings','설정 트리거'),c('image','이미지','radio',true),c('count','x1','radio',true),c('submit','생성 시작')],results:[],attachments:[],cost:'0 크레딧',settings:['모드: 이미지','수량: x1']};
 const browser:any={tab:()=>({id:'tab',url:page.url,revision:1}),activeId:()=>active,authCheck:async()=>auth,target:async()=> 'target',mediaPage:async()=>structuredClone(page),wait:async()=>{},tabs:()=>[]};
 const approvals:string[]=[];let core:Orchestrator;
 const permissions:any={cancel:()=>{},ask:async(a:any)=>{approvals.push(a.kind);return mutate?mutate(a.kind,page,core):true;}};
 const adapter:any={cancel:()=>{},target:async(_target:string,fn:any)=>fn(async(args:string[])=>{if(args[0]==='fill')page.editor!.value=args[2];if(args[1]==='#submit'){submits++;page.results=[{id:'new-result',selector:'#result',media:['https://media.example/result.png'],ready:true,busy:false,failed:false,downloads:[c('download','다운로드')]}];}if(args[1]==='#download'){const path=join(dir,'result.png');writeFileSync(path,png);store.artifact({id:'artifact',taskId:core.task!.id,name:'result.png',path,sourceUrl:'https://media.example/result.png',createdAt:Date.now(),status:'completed',bytes:png.length,mime:'image/png'});}return {};})};
 core=new Orchestrator(browser,adapter,store,permissions,()=>{});const task=await core.start('생성 검증','tab',undefined,true);const obs=await core.tool('browser.observe',{},task.id);
 const request={workflow:'media.generate',state:obs.state,requestId:'once',kind:'image',prompt:'보라색 정육면체',options:{count:1}};
 return {core,page,store,task,request,approvals,submits:()=>submits,auth:(v:boolean)=>auth=v,active:(v:string)=>active=v,close:()=>{core.dispose();store.close();assert.equal(dirname(resolve(dir)),resolve(tmpdir()));assert.ok(basename(dir).startsWith('honmoon-media-'));rmSync(dir,{recursive:true,force:true});}};
}
test('media site matching is exact and schemas reject arbitrary commands/options',()=>{
 assert.equal(mediaSite('https://grok.com/imagine'),'grok');assert.equal(mediaSite('https://grok.com.evil.test/imagine'),undefined);assert.equal(mediaSite('https://flow.google.com/project/x'),'flow');assert.equal(mediaSite('http://flow.google.com/project/x'),undefined);
 const request={workflow:'media.generate',state:'s',requestId:'r',kind:'image',prompt:'x'};assert.ok(mediaSchema.safeParse(request).success);for(const extra of [{approved:true},{options:{count:2}},{steps:[]},{fileIds:['a','b']},{options:{javascript:'alert(1)'}}])assert.equal(mediaSchema.safeParse({...request,...extra}).success,false);
 const legacy=executeToolSchema.parse({state:'s',requestId:'r',steps:[{target:'b1',action:'click'}]});assert.ok(executeSchema.safeParse(legacy).success,'MCP must not inject media defaults into legacy execution');
});
test('media workflow submits once, waits locally and verifies actual download',async()=>{const h=await harness();try{assert.equal(h.task.model,'gpt-6-luna');assert.equal(h.task.reasoningEffort,'high');const result=await h.core.tool('browser.execute',h.request,h.task.id);assert.ok(result.id);const job=await h.core.media.wait();assert.equal(job?.status,'succeeded',job?.error);assert.deepEqual(job?.artifactIds,['artifact']);assert.deepEqual(h.approvals,['batch','generation']);await h.core.tool('browser.execute',h.request,h.task.id);assert.equal(h.submits(),1);await assert.rejects(()=>h.core.tool('browser.execute',{...h.request,prompt:'different'},h.task.id),/같은 키/);}finally{h.close();}});
test('generation approval denial never submits',async()=>{const h=await harness(kind=>kind!=='generation');try{await h.core.tool('browser.execute',h.request,h.task.id);assert.equal((await h.core.media.wait())?.status,'failed');assert.equal(h.submits(),0);}finally{h.close();}});
test('changed prompt during final approval invalidates submission',async()=>{const h=await harness((kind,page)=>{if(kind==='generation')page.editor!.value='tampered';return true;});try{await h.core.tool('browser.execute',h.request,h.task.id);assert.match((await h.core.media.wait())?.error||'',/승인 후/);assert.equal(h.submits(),0);}finally{h.close();}});
test('changed cost during final approval invalidates submission',async()=>{const h=await harness((kind,page)=>{if(kind==='generation')page.cost='10 크레딧';return true;});try{await h.core.tool('browser.execute',h.request,h.task.id);assert.match((await h.core.media.wait())?.error||'',/비용/);assert.equal(h.submits(),0);}finally{h.close();}});
test('unknown cost requires a separate confirmation',async()=>{const h=await harness((kind,page)=>kind!=='unknown-cost');try{h.page.cost='비용 확인 불가';const o=await h.core.tool('browser.observe',{},h.task.id);await h.core.tool('browser.execute',{...h.request,state:o.state},h.task.id);await h.core.media.wait();assert.ok(h.approvals.includes('unknown-cost'));assert.equal(h.submits(),0);}finally{h.close();}});
test('cancellation between preparation and submission stops remaining commands',async()=>{const h=await harness((kind,_p,core)=>{if(kind==='generation')core.cancel('TEST_CANCEL');return true;});try{await h.core.tool('browser.execute',h.request,h.task.id);assert.equal((await h.core.media.wait())?.status,'cancelled');assert.equal(h.submits(),0);}finally{h.close();}});
test('media sites cannot use legacy mutations to bypass generation confirmation',async()=>{const h=await harness();try{await assert.rejects(()=>h.core.tool('browser.execute',{state:'x',requestId:'raw',steps:[{target:'b1',action:'click'}]},h.task.id),/media.generate/);await assert.rejects(()=>h.core.tool('capabilities.invoke',{id:'x'},h.task.id),/media.generate/);h.active('wrong');await assert.rejects(()=>h.core.tool('browser.execute',h.request,h.task.id),/활성/);h.active('tab');h.auth(true);await assert.rejects(()=>h.core.tool('browser.execute',h.request,h.task.id),/인증/);}finally{h.close();}});
test('unfinished media jobs recover as unknown without automatic execution',async()=>{const h=await harness();try{h.store.mediaJob({id:'old',taskId:'old',requestId:'r',digest:'d',site:'grok',version:'1',status:'submitted',createdAt:1,updatedAt:1,submittedAt:2,artifactIds:[],approvalMs:0,browserCommands:0});h.store.recoverMediaJobs();assert.equal(h.store.mediaJobs()[0].status,'unknown');assert.equal(h.submits(),0);}finally{h.close();}});
test('Luna high is validated and explicitly transmitted without disabling dynamic tools',async()=>{const calls:any[]=[];const codex=new CodexAdapter('unused','unused','unused',async()=>({}));codex.connect=async()=>{};codex.account={};codex.models=[{model:'gpt-6-luna',supportedReasoningEfforts:[{reasoningEffort:'high'}]}];codex.request=async(method,params)=>{calls.push({method,params});return method==='thread/start'?{thread:{id:'thread'}}:{turn:{id:'turn'}};};const t:any={id:'t',origin:'https://grok.com',prompt:'x',model:'gpt-6-luna',reasoningEffort:'high',executionMode:'compact'};await codex.run(t);assert.equal(calls[0].params.config.model_reasoning_effort,'high');assert.equal(calls[1].params.effort,'high');assert.equal(calls[0].params.dynamicTools.length,3);await assert.rejects(()=>codex.run({...t,model:'unavailable'}),/사용할 수 없습니다/);await assert.rejects(()=>codex.run({...t,reasoningEffort:'low'}),/지원하지 않습니다/);});
test('artifact validation rejects HTML masquerading as image/video',()=>{assert.ok(isImage(png));assert.equal(isImage(Buffer.from('<html>error</html>')),false);assert.equal(isVideo(png),false);});
test('duplicate option names stop instead of choosing a first match',async()=>{const h=await harness();try{h.page.controls.push(c('duplicate','이미지','radio',true));await h.core.tool('browser.execute',h.request,h.task.id);const job=await h.core.media.wait();assert.equal(job?.status,'failed');assert.equal(h.submits(),0);}finally{h.close();}});
test('unselected reference file is rejected before preparation approval',async()=>{const h=await harness();try{await assert.rejects(()=>h.core.tool('browser.execute',{...h.request,fileIds:['not-selected']},h.task.id),/선택한 파일/);assert.deepEqual(h.approvals,[]);assert.equal(h.submits(),0);}finally{h.close();}});
test('same-origin navigation to another project is rejected after approval',async()=>{const h=await harness((kind,p)=>{if(kind==='generation')p.url='https://flow.google.com/project/other';return true;});try{await h.core.tool('browser.execute',h.request,h.task.id);assert.match((await h.core.media.wait())?.error||'',/결과 화면 밖/);assert.equal(h.submits(),0);}finally{h.close();}});
test('multiple new result cards are unknown and never trigger another submission',async()=>{const h=await harness();try{const target=h.core.adapter.target.bind(h.core.adapter);h.core.adapter.target=async(id,fn)=>target(id,async run=>fn(async args=>{const result=await run(args);if(args[1]==='#submit')h.page.results.push({...h.page.results[0],id:'unrelated-result'});return result;}));await h.core.tool('browser.execute',h.request,h.task.id);const job=await h.core.media.wait();assert.equal(job?.status,'unknown');assert.equal(h.submits(),1);await assert.rejects(()=>h.core.tool('browser.execute',{...h.request,requestId:'retry'},h.task.id),/재제출/);}finally{h.close();}});
test('collapsed Grok composer reveals mode after approved prompt input without submitting',async()=>{const h=await harness();try{h.page.site='grok';h.page.url='https://grok.com/imagine';h.task.origin='https://grok.com';h.core.task!.origin='https://grok.com';h.page.controls=[c('submit','제출')];const target=h.core.adapter.target.bind(h.core.adapter);h.core.adapter.target=async(id,fn)=>target(id,async run=>fn(async args=>{if(args[0]==='fill'){assert.ok(h.approvals.includes('batch'));assert.equal(h.submits(),0);}const result=await run(args);if(args[0]==='fill')h.page.controls.push(c('image','이미지','radio',true));return result;}));const o=await h.core.tool('browser.observe',{},h.task.id);await h.core.tool('browser.execute',{...h.request,state:o.state},h.task.id);const job=await h.core.media.wait();assert.equal(job?.status,'succeeded',job?.error);assert.equal(h.submits(),1);assert.deepEqual(h.approvals,['batch','generation']);}finally{h.close();}});
test('whole-task approval completes a verified media job without repeated prompts',async()=>{const h=await harness();try{const p=new Permissions(()=>{});h.core.permissions=p;h.core.authorizeTask(h.task.id,{allowUnknownCost:true,generationLimit:1});h.page.cost='비용 확인 불가';const o=await h.core.tool('browser.observe',{},h.task.id);await h.core.tool('browser.execute',{...h.request,state:o.state},h.task.id);assert.equal((await h.core.media.wait())?.status,'succeeded');assert.equal(p.list().length,0);await h.core.reviewCompletion('local verified');assert.equal(h.store.tasks()[0].status,'succeeded');assert.equal(p.taskGrant(h.task.id),undefined);assert.equal(h.submits(),1);}finally{h.close();}});
test('whole-task file grant excludes files selected later and does not infer success',async()=>{const h=await harness();try{h.core.permissions=new Permissions(()=>{});h.core.authorizeTask(h.task.id,{allowUnknownCost:false,generationLimit:1});assert.throws(()=>h.core.assertFileApproved('later-file'),/승인 이후/);await h.core.reviewCompletion('model says done');assert.equal(h.store.tasks()[0].status,'failed');assert.match(h.store.tasks()[0].error||'',/RESULT_UNVERIFIED/);}finally{h.close();}});

test('prompt normalization preserves meaningful paragraph and trailing newline differences',()=>{assert.equal(normalizePrompt('첫째\r\n둘째\u00a0줄'),'첫째\n둘째 줄');assert.notEqual(normalizePrompt('첫째\n둘째'),normalizePrompt('첫째 둘째'));assert.notEqual(normalizePrompt('x\n'),normalizePrompt('x'));});
test('layout movement keeps the same node identity and executes its fresh selector',async()=>{const h=await harness();try{const target=h.core.adapter.target.bind(h.core.adapter);h.core.adapter.target=async(id,fn)=>{h.page.controls.find(c=>c.key==='settings')!.selector='#moved-settings';return target(id,fn);};await h.core.tool('browser.execute',h.request,h.task.id);assert.equal((await h.core.media.wait())?.status,'succeeded');}finally{h.close();}});
test('node replacement during target focus still stops before mutation',async()=>{const h=await harness();try{const target=h.core.adapter.target.bind(h.core.adapter);h.core.adapter.target=async(id,fn)=>{h.page.controls.find(c=>c.key==='settings')!.key='replacement';return target(id,fn);};await h.core.tool('browser.execute',h.request,h.task.id);assert.match((await h.core.media.wait())?.error||'',/対象|대상/);assert.equal(h.submits(),0);}finally{h.close();}});
test('image-to-video requires two remaining submissions before changing the page',async()=>{const h=await harness();try{h.page.site='grok';h.page.url='https://grok.com/imagine';h.core.task!.origin='https://grok.com';h.core.permissions=new Permissions(()=>{});h.core.authorizeTask(h.task.id,{allowUnknownCost:true,generationLimit:1});const obs=await h.core.tool('browser.observe',{},h.task.id);await assert.rejects(()=>h.core.tool('browser.execute',{...h.request,state:obs.state,kind:'image_to_video'},h.task.id),/생성 2회/);assert.equal(h.submits(),0);assert.equal(h.page.editor!.value,'');}finally{h.close();}});
test('unknown existing-result ID cannot be used as a video reference',async()=>{const h=await harness();try{h.page.site='grok';h.page.url='https://grok.com/imagine';h.core.task!.origin='https://grok.com';const obs=await h.core.tool('browser.observe',{},h.task.id);await assert.rejects(()=>h.core.tool('browser.execute',{...h.request,state:obs.state,kind:'video',sourceResultId:'11111111-2222-4333-8444-555555555555'},h.task.id),/원본 이미지/);assert.equal(h.submits(),0);}finally{h.close();}});
