import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store,redact,safeUrl} from '../packages/core/store.js';
import {Permissions} from '../packages/core/permissions.js';
import {discover} from '../packages/capabilities/index.js';
import {invokeSchema} from '../packages/core/orchestrator.js';
import {tools,disabledFeatures} from '../packages/codex-adapter/index.js';
import {spawnSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
test('abrupt writer process exit preserves recovery record',()=>{const file=join(mkdtempSync(join(tmpdir(),'honmoon-crash-')),'test.db');const script=`import {Store} from ${JSON.stringify(pathToFileURL(resolve('packages/core/store.ts')).href)};const s=new Store(${JSON.stringify(file)});s.task({id:'crashed',tabId:'x',origin:'https://example.com',prompt:'test',status:'awaiting_approval',createdAt:1,updatedAt:1,expiresAt:99999});process.exit(77)`;const r=spawnSync(process.execPath,['--import','tsx','--input-type=module','-e',script]);assert.equal(r.status,77,r.stderr?.toString());const reopened=new Store(file);assert.equal(reopened.tasks()[0].status,'cancelled');assert.equal(reopened.tasks()[0].error,'APP_RESTARTED');reopened.close();});
test('restart cancels unfinished tasks without replay',()=>{const file=join(mkdtempSync(join(tmpdir(),'honmoon-')),'test.db');const store=new Store(file);store.task({id:'1',tabId:'a',origin:'https://example.com',prompt:'test',status:'running',createdAt:1,updatedAt:1,expiresAt:999999});store.close();const reopened=new Store(file);assert.equal(reopened.tasks()[0].status,'cancelled');assert.equal(reopened.tasks()[0].error,'APP_RESTARTED');reopened.close();});
test('approvals are single use and cancellation denies unresolved requests',async()=>{const p=new Permissions(()=>{});const first=p.ask({kind:'click',title:'test',detail:'',binding:'one'});const id=p.list()[0].id;p.decide(id,true);p.decide(id,false);assert.equal(await first,true);const second=p.ask({taskId:'t',kind:'fill',title:'test',detail:'',binding:'two'});p.cancel('t');assert.equal(await second,false);assert.equal(p.list().length,0);});
test('redaction and URL metadata exclude typical credentials',()=>{assert.equal(safeUrl('https://user:secret@example.com/path?token=abc#private'),'https://example.com/path');assert.ok(!redact('password=secret authorization=Bearer_cookie').includes('secret'));assert.match(redact('sk-12345678901234567'),/REDACTED/);});
test('discovery excludes credential fields and invalidates on navigation',()=>{const tab={id:'t',targetId:'x',title:'',url:'https://example.com',revision:1,authPaused:false,loading:false};const snapshot={refs:{e1:{role:'textbox',name:'Password'},e2:{role:'button',name:'Generate'}}};const one=discover(tab,snapshot);assert.equal(one.length,1);assert.equal(one[0].reviewed,false);assert.equal(one[0].approval,'required');assert.notEqual(one[0].id,discover({...tab,revision:2},snapshot)[0].id);});
test('invocation cannot smuggle raw selectors paths or approval',()=>{for(const payload of [{id:'a',input:{path:'C:/secret'},requestId:'x'},{id:'a',input:{},requestId:'x',approved:true},{id:'a',input:{},requestId:'x',selector:'body'}])assert.equal(invokeSchema.safeParse(payload).success,false);});
test('Codex tool surface has no shell, eval, auth, or self approval',()=>{assert.ok(disabledFeatures.includes('shell_tool'));assert.ok(disabledFeatures.includes('browser_use'));assert.ok(disabledFeatures.includes('plugins'));assert.deepEqual(tools.map(t=>t.name).sort(),['honmoon_artifacts_list','honmoon_capabilities_find','honmoon_capabilities_inspect','honmoon_capabilities_invoke','honmoon_capabilities_list','honmoon_page_read','honmoon_page_inspect','honmoon_tasks_status'].sort());});
