import {z} from 'zod';
export const mediaOptions=z.object({model:z.string().max(100).optional(),aspectRatio:z.enum(['1:1','16:9','9:16','4:3','3:4','2:3','3:2']).optional(),resolution:z.string().max(40).optional(),duration:z.string().max(30).optional(),audio:z.boolean().optional(),count:z.literal(1).default(1)}).strict();
export const mediaSchema=z.object({workflow:z.literal('media.generate'),state:z.string().min(1).max(80),requestId:z.string().min(1).max(100),kind:z.enum(['image','video','image_to_video']),prompt:z.string().min(1).max(6000),sourceResultId:z.string().uuid().optional(),fileIds:z.array(z.string().max(80)).max(1).default([]),options:mediaOptions.default({}),download:z.literal(true).default(true)}).strict();
export type MediaRequest=z.infer<typeof mediaSchema>;
export type MediaSite='grok'|'flow';
export function mediaSite(url:string):MediaSite|undefined{try{const u=new URL(url);if(u.protocol!=='https:')return;if(u.hostname==='grok.com'&&/^\/imagine(?:\/|$)/.test(u.pathname))return 'grok';if((u.hostname==='flow.google.com'&&/^\/project\//.test(u.pathname))||(u.hostname==='labs.google'&&/^\/fx\/(?:[a-z-]+\/)?tools\/flow\/project\//.test(u.pathname)))return 'flow';}catch{}}
export const mediaRules={
 grok:{version:'2026-09-28.2',editor:'[contenteditable="true"][aria-label="Ask Grok anything"]',submit:['제출','Submit','생성','Generate','이미지 생성','Create image','동영상 생성','Create video','보내기','Send'],settings:[],upload:['업로드','Upload'],mode:{image:['이미지','Image'],video:['비디오','Video']},menus:{aspectRatio:['종횡비','Aspect ratio'],resolution:['비디오 해상도','Video resolution'],duration:['동영상 길이','Video length'],model:['모델','Model']},download:['다운로드','Download','이미지 다운로드','Download image','동영상 다운로드','Download video']},
 flow:{version:'2026-09-28.2',editor:'.ProseMirror[contenteditable="true"]',submit:['생성 시작','Generate','Start generation'],settings:['설정 트리거','Settings'],upload:['프롬프트 상자에 소재 추가','Add assets to prompt','업로드','Upload'],mode:{image:['이미지','Image'],video:['동영상','Video']},menus:{aspectRatio:['가로세로 비율','Aspect ratio'],resolution:['해상도','Resolution'],duration:['길이','Duration'],model:['모델 제품군 선택','Select model family']},download:['다운로드','Download','원본 다운로드','Download original']}
} as const;
export type MediaControl={key:string;selector:string;name:string;role:string;focused?:boolean;scope:string;value:string;checked:boolean;disabled:boolean;hidden:boolean};
export type MediaResult={id:string;selector:string;media:string[];imageMedia?:string[];videoMedia?:string[];ready:boolean;busy:boolean;failed:boolean;downloads:MediaControl[];opener?:MediaControl};
export type MediaPage={site:MediaSite;version:string;url:string;editor?:MediaControl;controls:MediaControl[];results:MediaResult[];attachments:string[];cost:string;settings:string[];problem?:string};
export type MediaJob={id:string;taskId:string;requestId:string;digest:string;site:MediaSite;version:string;phase?:'image'|'video';submissions?:{kind:string;at:number;sourceResultId?:string}[];status:'preparing'|'awaiting_approval'|'submitted'|'running'|'downloading'|'succeeded'|'failed'|'unknown'|'cancelled';createdAt:number;updatedAt:number;submittedAt?:number;resultId?:string;artifactIds:string[];error?:string;approvalMs:number;browserCommands:number};
export const mediaTerminal=(s:MediaJob['status'])=>['succeeded','failed','unknown','cancelled'].includes(s);
