import {randomUUID} from 'node:crypto';
import {readFileSync,statSync} from 'node:fs';
import {hash} from '../capabilities/index.js';
import {mediaRules,mediaSchema,mediaSite,mediaTerminal,type MediaControl,type MediaPage,type MediaJob,type MediaRequest} from './media-contract.js';
import type {Orchestrator} from './orchestrator.js';
import {fail} from './types.js';
import {safeUrl} from './store.js';

import {MediaDownloadGate} from './media-download.js';
export class MediaRunner{
 private downloads=new MediaDownloadGate();
 claimDownload(tabId:string,url:string,name:string){if(!this.busy()||this.active?.status!=='downloading'||this.core.task?.tabId!==tabId)return;return this.downloads.claim(tabId,url,name);}
 active?:MediaJob;private completion?:Promise<MediaJob>;private resolve?: (job:MediaJob)=>void;private stopped=false;private deadline=Infinity;private deadlineTimer?:ReturnType<typeof setTimeout>;private initialUrl='';
 constructor(private core:Orchestrator){}
 private save(){if(this.active){this.active.updatedAt=Date.now();this.core.store.mediaJob(this.active);this.core.changed();}}
 private async guard(taskId:string){this.core.assert(taskId);if(this.active?.taskId===taskId){if(this.stopped)fail('CANCELLED','생성 제어가 중단되었습니다.');if(!mediaTerminal(this.active.status)&&Date.now()>this.deadline)fail('PHASE_TIMEOUT','실행 단계 제한 시간을 초과했습니다.');const url=this.core.browser.tab(this.core.task!.tabId).url;if(this.initialUrl&&url!==this.initialUrl){const initial=new URL(this.initialUrl),now=new URL(url);const allowed=this.active.submittedAt&&initial.origin===now.origin&&(this.active.site==='flow'?now.pathname.startsWith(initial.pathname.replace(/\/$/,'')+'/edit/'): /^\/imagine\/post\/[a-zA-Z0-9-]+\/?$/.test(now.pathname));if(!allowed)fail('UNEXPECTED_NAVIGATION','허용한 생성 결과 화면 밖으로 이동했습니다.');}}if(await this.core.browser.authCheck(this.core.task!.tabId))fail('AUTH_REQUIRED','인증 보호 중입니다.');this.core.assert(taskId);}
 private armDeadline(taskId:string,ms:number){clearTimeout(this.deadlineTimer);this.deadline=Date.now()+ms;this.deadlineTimer=setTimeout(()=>{if(this.busy()&&this.active?.taskId===taskId){this.core.permissions.cancel(taskId);this.core.adapter.cancel();}},ms);}
 private async page(taskId:string,requireEditor=true){await this.guard(taskId);const t=this.core.task!;if(!this.core.browser.mediaPage)fail('UNSUPPORTED_SCREEN','생성 페이지 관측기가 없습니다.');const p=await this.core.browser.mediaPage(t.tabId);await this.guard(taskId);if(!p||(requireEditor&&p.problem))fail('UNSUPPORTED_SCREEN',p?.problem||'지원하지 않는 생성 화면입니다.');return p;}
 private state(p:MediaPage){return hash([p.url,p.version,p.editor&&this.identity(p.editor),p.settings,p.cost,p.attachments]).slice(0,24);}
 private identity(c:MediaControl){return [c.key,c.name,c.role,c.scope,c.role==='textbox'?normalizePrompt(c.value):undefined,c.checked,c.disabled,c.hidden];}
 private source(p:MediaPage,id:string){const matches=p.results.filter(r=>r.id===id&&r.ready&&!r.busy&&(r.imageMedia?.length||0)>0);if(p.site!=='grok'||new URL(p.url).pathname!==`/imagine/post/${id}`||matches.length!==1)fail('SOURCE_NOT_VERIFIED','현재 결과 화면의 원본 이미지 ID를 확인하지 못했습니다.');const image=matches[0];if(p.attachments.length!==1||!image.imageMedia!.some(u=>safeUrl(u)===safeUrl(p.attachments[0])))fail('SOURCE_NOT_VERIFIED','편집기에 첨부된 이미지가 선택한 결과와 다릅니다.');return image;}
 private async verifyPrompt(j:MediaJob,prompt:string){for(let n=0;n<12;n++){const p=await this.page(j.taskId);if(p.editor&&normalizePrompt(p.editor.value)===normalizePrompt(prompt))return p;await this.core.browser.wait(100);}fail('INPUT_NOT_VERIFIED','프롬프트 입력값 불일치');}
 async observe(){const t=this.core.assert();if(!mediaSite(this.core.browser.tab(t.tabId).url))return undefined;if(this.busy())return {workflow:'media.generate',support:'busy',job:this.publicJob(this.active!)};try{const p=await this.page(t.id);return {workflow:'media.generate',state:this.state(p),site:p.site,ruleVersion:p.version,support:'experimental',kinds:p.site==='grok'?['image','video','image_to_video']:['image','video'],sourceResultId:p.site==='grok'&&p.attachments.length===1?p.results.find(r=>r.imageMedia?.some(u=>safeUrl(u)===safeUrl(p.attachments[0])))?.id:undefined,defaultVideoResolution:p.site==='grok'?'480p':undefined,referenceImages:1,count:1,options:['model','aspectRatio','resolution','duration','audio'],currentSettings:p.settings,cost:p.cost,job:this.active?.taskId===t.id?this.publicJob(this.active):undefined};}catch(e){return {workflow:'media.generate',support:'unsupported_screen',reason:(e as Error).message};}}
 publicJob(j:MediaJob){return {id:j.id,site:j.site,status:j.status,phase:j.phase,submissions:j.submissions?.length||0,resultId:j.resultId,artifactIds:j.artifactIds,error:j.error,approvalMs:j.approvalMs,browserCommands:j.browserCommands};}
 wait(){return this.completion;}
 busy(){return !!this.active&&!mediaTerminal(this.active.status);}
 cancel(reason:string){if(!this.busy())return;this.downloads.clear();this.stopped=true;this.active!.status='cancelled';this.active!.error=reason+'; 이미 접수된 사이트 생성은 계속될 수 있습니다.';this.save();}
 async execute(raw:unknown){const p=mediaSchema.parse(raw);const t=this.core.assert();const digest=hash(p);const old=this.core.store.mediaJobs().find(j=>j.taskId===t.id&&j.requestId===p.requestId);if(old){if(old.digest!==digest)fail('REQUEST_CONFLICT','같은 키의 생성 요청이 변경되었습니다.');return this.publicJob(old);}
  if(this.busy()||this.core.executor.busy)fail('EXECUTOR_BUSY','이미 실행 중입니다.');if(this.core.store.mediaJobs().some(j=>j.taskId===t.id&&['unknown','cancelled'].includes(j.status)))fail('OUTCOME_UNKNOWN','결과 불명확한 생성은 자동 재제출하지 않습니다.');
  const page=await this.page(t.id);if(p.kind==='image_to_video'&&(page.site!=='grok'||p.sourceResultId))fail('UNSUPPORTED_WORKFLOW','이미지 생성 후 영상 변환은 Grok 새 생성 화면에서만 지원합니다. 기존 이미지는 kind video와 sourceResultId를 사용하세요.');if(p.sourceResultId){if(p.kind!=='video'||p.fileIds.length)fail('SOURCE_CONFLICT','기존 결과 영상 변환에는 추가 파일을 함께 사용할 수 없습니다.');this.source(page,p.sourceResultId);}if(p.kind==='image_to_video'){const grant=this.core.permissions.taskGrant?.(t.id);if(grant&&grant.generationLimit-grant.generationsUsed<2)fail('APPROVAL_LIMIT','이미지 생성 후 영상 변환은 생성 2회가 필요합니다. 작업 전체 승인 한도를 2회 이상으로 설정하세요.');}if(page.site==='flow'&&/\/edit\//.test(new URL(page.url).pathname))fail('UNSUPPORTED_SCREEN','프로젝트 목록 화면에서 생성 작업을 시작하세요.');if(this.state(page)!==p.state)fail('STALE_STATE','생성 화면을 다시 관측하세요.');for(const id of p.fileIds)this.file(id);
  this.stopped=false;this.initialUrl=page.url;this.active={id:randomUUID(),taskId:t.id,requestId:p.requestId,digest,site:page.site,version:page.version,status:'preparing',createdAt:Date.now(),updatedAt:Date.now(),artifactIds:[],approvalMs:0,browserCommands:0};this.armDeadline(t.id,120000);this.save();this.completion=new Promise(resolve=>{this.resolve=resolve;});const job=this.active;const resolve=this.resolve;
  void this.run(job,p).catch(e=>{if(!mediaTerminal(job.status)){job.status=job.submittedAt?'unknown':'failed';job.error=(e as Error).message;this.core.markRecoverable();this.save();}}).finally(()=>{this.downloads.clear();if(this.active===job)clearTimeout(this.deadlineTimer);if(job.status!=='cancelled'){this.core.store.mediaJob(job);this.core.changed();}resolve?.({...job});});return {...this.publicJob(job),message:'로컬 실행기가 승인·생성·다운로드를 진행합니다. 재제출하지 마세요. 작업창에서 결과를 받습니다.'};
 }
 private file(id:string){this.core.assertFileApproved(id);const f=this.core.files.get(id);if(!f)fail('FILE_NOT_ALLOWED','사용자가 선택한 파일 ID가 필요합니다.');const bytes=readFileSync(f.path);if(statSync(f.path).size!==f.size||hashBytes(bytes)!==f.digest)fail('FILE_CHANGED','선택한 파일이 변경되었습니다.');if(!isImage(bytes))fail('FILE_INVALID','참조 파일은 PNG/JPEG/WebP 이미지여야 합니다.');return f;}
 private async approve(j:MediaJob,kind:string,title:string,details:unknown){await this.guard(j.taskId);j.status='awaiting_approval';this.core.task!.status='awaiting_approval';this.core.update();this.save();const start=Date.now();const allowed=await this.core.permissions.ask({taskId:j.taskId,kind,title,detail:typeof details==='string'?details:JSON.stringify(details,null,2),binding:hash([j.taskId,j.digest,details])});j.approvalMs+=Date.now()-start;await this.guard(j.taskId);this.core.task!.status='running';this.core.update();if(!allowed)fail('PERMISSION_DENIED','사용자가 생성 작업을 거절했습니다.');j.status='preparing';this.save();}
 private one(p:MediaPage,names:readonly string[],roles?:string[]){const found=p.controls.filter(c=>!c.hidden&&!c.disabled&&names.includes(c.name)&&(!roles||roles.includes(c.role)));if(found.length!==1)fail('UNSUPPORTED_SCREEN','대상이 없거나 여러 개입니다: '+names.join(' / '));return found[0];}
 private async command(j:MediaJob,c:MediaControl,action:'click'|'fill'|'upload',value?:string){await this.guard(j.taskId);const fresh=await this.page(j.taskId,!j.submittedAt);const actual=[fresh.editor,...fresh.controls,...fresh.results.flatMap(r=>[r.opener,...r.downloads])].find(x=>x?.key===c.key);if(!actual||hash(this.identity(actual))!==hash(this.identity(c)))fail('TARGET_REPLACED','실행 대상이 변경되었습니다.');const target=await this.core.browser.target(this.core.task!.tabId);await this.core.adapter.target(target,async run=>{await this.guard(j.taskId);const again=await this.page(j.taskId,!j.submittedAt);const same=[again.editor,...again.controls,...again.results.flatMap(r=>[r.opener,...r.downloads])].find(x=>x?.key===c.key);if(!same||hash(this.identity(same))!==hash(this.identity(c)))fail('TARGET_REPLACED','실행 직전 대상이 변경되었습니다.');if(action==='fill'&&same.value){
   // Native agent-browser fill can insert into an existing contenteditable value.
   // Clear only a freshly checked, focused editor, then require an empty value.
   j.browserCommands++;await run(['click',same.selector]);
   let editor=(await this.page(j.taskId)).editor;if(!editor||editor.key!==same.key||!editor.focused)fail('EDITOR_FOCUS','프롬프트 편집기 포커스를 확인하지 못했습니다.');
   j.browserCommands++;await run(['press','Control+A']);await this.guard(j.taskId);
   editor=(await this.page(j.taskId)).editor;if(!editor||editor.key!==same.key||!editor.focused)fail('EDITOR_FOCUS','프롬프트 편집기 포커스가 변경되었습니다.');
   j.browserCommands++;await run(['press','Backspace']);
   editor=(await this.page(j.taskId)).editor;if(!editor||editor.key!==same.key||normalizePrompt(editor.value)!=='')fail('INPUT_NOT_CLEARED','기존 프롬프트를 비우지 못했습니다.');
   same.selector=editor.selector;
  }j.browserCommands++;this.save();await run([action,same.selector,...(value===undefined?[]:[value])]);});await this.guard(j.taskId);}
 private async escape(j:MediaJob){await this.guard(j.taskId);const target=await this.core.browser.target(this.core.task!.tabId);await this.core.adapter.target(target,async c=>{await this.guard(j.taskId);j.browserCommands++;await c(['press','Escape']);});}
 private async choose(j:MediaJob,names:readonly string[],menu?:readonly string[]){let page=await this.page(j.taskId);let candidates=page.controls.filter(c=>!c.hidden&&['radio','menuitemradio','option','menuitem'].includes(c.role)&&names.some(n=>optionName(c.name)===optionName(n)));if(candidates.length===0&&menu?.length){await this.command(j,this.one(page,menu),'click');page=await this.page(j.taskId);candidates=page.controls.filter(c=>!c.hidden&&['radio','menuitemradio','option','menuitem'].includes(c.role)&&names.some(n=>optionName(c.name)===optionName(n)));}if(candidates.length!==1)fail('UNSUPPORTED_OPTION','선택지를 유일하게 찾지 못했습니다: '+names.join('/'));const c=candidates[0];if(!c.checked){await this.command(j,c,'click');let after=await this.page(j.taskId);let selected=after.controls.find(x=>x.key===c.key);if(!selected&&menu?.length){await this.command(j,this.one(after,menu),'click');after=await this.page(j.taskId);const matches=after.controls.filter(x=>x.name===c.name&&x.role===c.role&&x.scope===c.scope);if(matches.length===1)selected=matches[0];}if(!selected?.checked)fail('OPTION_NOT_VERIFIED','선택 상태를 확인하지 못했습니다: '+c.name);}}
 private async run(j:MediaJob,req:MediaRequest){
  if(req.kind==='image_to_video'){const imageReq={...req,kind:'image' as const,options:{count:1 as const,aspectRatio:req.options.aspectRatio}};const result=await this.runPhase(j,imageReq,true);if(!result)fail('SOURCE_NOT_VERIFIED','이미지 생성 결과가 없습니다.');if(result.opener)await this.command(j,result.opener,'click');const p=await this.page(j.taskId);this.source(p,result.id);this.armDeadline(j.taskId,120000);await this.runPhase(j,{...req,kind:'video',sourceResultId:result.id,fileIds:[]});return;}
  await this.runPhase(j,req);
 }
 private async runPhase(j:MediaJob,request:MediaRequest,chainImage=false){const req={...request,options:{...request.options}};j.phase=req.kind==='video'?'video':'image';j.status='preparing';this.save();let p=await this.page(j.taskId);if(p.site==='grok'&&req.kind==='video'&&!req.options.resolution)req.options.resolution='480p';const rule=mediaRules[p.site];const prepareStart=Date.now();
  await this.approve(j,'batch','생성 준비 승인',{site:p.url,prompt:req.prompt,kind:req.kind,files:req.fileIds.map(id=>this.file(id).name),options:req.options,readScope:'현재 생성 설정·접수 상태·이번 결과·다운로드'});
  // Grok initially collapses the composer and hides its mode controls. Filling
  // the approved prompt expands it without submitting or guessing a mode.
  if(p.site==='grok'){p=await this.page(j.taskId);if(normalizePrompt(p.editor?.value||'')!==normalizePrompt(req.prompt))await this.command(j,p.editor!,'fill',req.prompt);p=await this.verifyPrompt(j,req.prompt);}
  if(rule.settings.length)await this.command(j,this.one(await this.page(j.taskId),rule.settings),'click');
  await this.choose(j,rule.mode[req.kind==='video'?'video':'image']);
  for(const key of ['model','aspectRatio','resolution','duration'] as const){const value=req.options[key];if(value){const labels=key==='aspectRatio'?[value,...({'1:1':['1:1정사각형','1:1 정사각형'],'16:9':['16:9와이드스크린','16:9 와이드스크린'],'9:16':['9:16수직','9:16 수직'],'2:3':['2:3긴 세로'],'3:2':['3:2와이드']} as Record<string,string[]>)[value]||[]]:[value];await this.choose(j,labels,rule.menus[key]);}}
  if(p.site==='flow')await this.choose(j,['x1','1']);
  if(req.options.audio!==undefined){const c=this.one(await this.page(j.taskId),['비디오 오디오','Video audio'],['checkbox','button']);if(c.checked!==req.options.audio)await this.command(j,c,'click');if(this.one(await this.page(j.taskId),['비디오 오디오','Video audio'],['checkbox','button']).checked!==req.options.audio)fail('OPTION_NOT_VERIFIED','오디오 설정 불일치');}
  p=await this.page(j.taskId);const selectedSettings=p.settings;const cost=p.cost;await this.escape(j);p=await this.page(j.taskId);
  if(req.sourceResultId)this.source(p,req.sourceResultId);else if(p.attachments.length)fail('EXISTING_ATTACHMENT','기존 첨부 이미지를 직접 제거한 뒤 새 작업을 시작하세요.');
  for(const fileId of req.fileIds){const f=this.file(fileId);await this.approve(j,'upload','참조 이미지 전송 승인',{site:p.url,file:f.name,digest:f.digest});p=await this.page(j.taskId);const fields=p.controls.filter(c=>c.role==='file');if(fields.length===1)await this.command(j,fields[0],'upload',this.file(fileId).path);else if(fields.length===0&&p.site==='flow'&&this.core.browser.chooseApprovedFile){await this.command(j,this.one(p,['프롬프트 상자에 소재 추가','Add assets to prompt']),'click');p=await this.page(j.taskId);const upload=this.one(p,['미디어 업로드','Upload media']);await this.core.browser.chooseApprovedFile(this.core.task!.tabId,this.file(fileId).path,()=>this.command(j,upload,'click'),async()=>{await this.guard(j.taskId);this.file(fileId);});}else fail('UNSUPPORTED_UPLOAD','편집기에 연결된 파일 입력을 유일하게 찾지 못했습니다.');const until=Date.now()+10000;do{p=await this.page(j.taskId);if(p.attachments.length===1)break;await this.core.browser.wait(250);}while(Date.now()<until);if(p.attachments.length!==1)fail('UPLOAD_NOT_VERIFIED','참조 이미지 첨부 완료를 확인하지 못했습니다.');}
  p=await this.page(j.taskId);if(normalizePrompt(p.editor?.value||'')!==normalizePrompt(req.prompt))await this.command(j,p.editor!,'fill',req.prompt);p=await this.verifyPrompt(j,req.prompt);if(Date.now()-prepareStart>120000)fail('PREPARATION_TIMEOUT','준비 단계 제한 시간을 초과했습니다.');
  const submit=this.one(p,rule.submit,['button']);const baseline=p.results.map(r=>({id:r.id,media:r.media}));const binding=hash([p.editor&&this.identity(p.editor),p.settings,p.attachments,p.cost,this.identity(submit)]);
  this.armDeadline(j.taskId,120000);await this.approve(j,'generation','생성 1회 제출 승인',{site:p.url,kind:req.kind,sourceResultId:req.sourceResultId,prompt:req.prompt,files:req.fileIds.map(id=>this.file(id).name),settings:selectedSettings,requested:req.options,cost,quantity:p.site==='flow'?1:'제출 1회 · Grok의 실제 출력 수는 사이트 설정에 따릅니다.',note:'한 번만 제출합니다. 결과가 불명확하면 자동 재생성하지 않습니다.'});
  if(cost==='비용 확인 불가')await this.approve(j,'unknown-cost','표시되지 않은 생성 비용 확인','사이트에서 비용을 확인하지 못했습니다. 계정의 요금·크레딧 사용 가능성을 확인한 경우에만 이 생성 1회를 승인하세요.');
  if(rule.settings.length){await this.command(j,this.one(await this.page(j.taskId),rule.settings),'click');const checkSettings=await this.page(j.taskId);if(hash(checkSettings.settings)!==hash(selectedSettings)||checkSettings.cost!==cost)fail('APPROVAL_STALE','승인 후 생성 옵션 또는 비용이 변경되었습니다.');await this.escape(j);}
  p=await this.page(j.taskId);if(binding!==hash([p.editor&&this.identity(p.editor),p.settings,p.attachments,p.cost,this.identity(this.one(p,rule.submit,['button']))]))fail('APPROVAL_STALE','승인 후 입력·설정·비용·대상이 변경되었습니다.');for(const id of req.fileIds)this.file(id);if(req.sourceResultId)this.source(p,req.sourceResultId);
  j.submittedAt=Date.now();(j.submissions??=[]).push({kind:req.kind,at:j.submittedAt,sourceResultId:req.sourceResultId});j.status='submitted';this.armDeadline(j.taskId,600000);this.save();await this.command(j,this.one(p,rule.submit,['button']),'click');
  const deadline=j.submittedAt+600000;let result:MediaPage['results'][number]|undefined;
  while(Date.now()<deadline){await this.guard(j.taskId);p=await this.page(j.taskId,false);const fresh=p.results.filter(r=>!baseline.some(b=>b.id===r.id&&hash(b.media)===hash(r.media)));if(fresh.length>1)fail('AMBIGUOUS_RESULT','새 결과가 여러 개여서 이번 생성과 연결할 수 없습니다.');if(fresh.length===1){const r=fresh[0];if(r.failed){j.status='failed';fail('GENERATION_FAILED','사이트에서 생성 실패를 표시했습니다.');}if(r.busy){j.status='running';this.save();}const kindMatches=req.kind==='video'?(r.videoMedia?.length||0)>0:r.imageMedia===undefined||r.imageMedia.length>0;if(r.ready&&!r.busy&&kindMatches){result=r;break;}}
   await this.core.browser.wait(Date.now()-j.submittedAt<30000?2000:5000);
  }
  if(!result)fail('OUTCOME_UNKNOWN','10분 내 이번 생성 결과를 확인하지 못했습니다. 재제출하지 않습니다.');j.resultId=result.id;this.save();if(chainImage)return result;
  this.armDeadline(j.taskId,60000);if(result.downloads.length===0&&result.opener){await this.command(j,result.opener,'click');p=await this.page(j.taskId,false);const same=p.results.find(r=>r.id===result!.id);if(!same)fail('RESULT_CHANGED','결과 상세 화면의 미디어 ID가 일치하지 않습니다.');result=same;}
  if(result.downloads.length!==1)fail('DOWNLOAD_UNAVAILABLE','이번 결과의 다운로드 버튼을 유일하게 식별하지 못했습니다.');j.status='downloading';this.save();
  const since=Date.now();const downloadToken=this.downloads.arm(this.core.task!.tabId,result.id,this.core.task!.origin);const download=result.downloads[0];await this.command(j,download,'click');if(['미디어 다운로드','Download media'].includes(download.name)){p=await this.page(j.taskId,false);const originals=p.controls.filter(c=>c.role==='menuitem'&&!c.disabled&&!c.hidden&&/원본\s*크기|Original\s*size/i.test(c.name));if(originals.length!==1)fail('UNSUPPORTED_DOWNLOAD_MENU','원본 다운로드 항목을 유일하게 찾지 못했습니다.');await this.command(j,originals[0],'click');}const until=Date.now()+60000;
  while(Date.now()<until){await this.guard(j.taskId);const arts=this.core.store.artifacts().filter(a=>a.taskId===j.taskId&&a.createdAt>=since);if(arts.some(a=>a.status==='interrupted'))fail('DOWNLOAD_FAILED','다운로드가 중단되었습니다.');if(arts.length===1&&arts[0].status==='completed'){const a=arts[0];const source=safeUrl(a.sourceUrl);const linked=a.mediaBinding===downloadToken||(req.kind==='video'?result.videoMedia||[]:result.imageMedia||result.media).some(url=>safeUrl(url)===source)||(result.id.length>=16&&result.media.some(url=>{try{return new URL(url).origin===new URL(source).origin&&new URL(source).pathname.split('/').includes(result!.id);}catch{return false;}}));if(!linked)fail('ARTIFACT_UNBOUND','다운로드 주소를 이번 생성 결과와 연결하지 못했습니다.');const b=readFileSync(a.path);if(b.length!==a.bytes||!b.length||!(req.kind==='image'?isImage(b):isVideo(b)))fail('ARTIFACT_INVALID','다운로드 파일의 크기·형식 검증 실패');j.artifactIds=[a.id];j.status='succeeded';this.save();return;}await this.core.browser.wait(250);}
  fail('DOWNLOAD_TIMEOUT','다운로드 완료를 확인하지 못했습니다.');
 }
}
import {createHash} from 'node:crypto';
export const normalizePrompt=(s:string)=>s.replace(/\r\n?/g,'\n').replace(/\u00a0/g,' ');
const optionName=(s:string)=>s.replace(/\s+/g,'');
const hashBytes=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
export const isImage=(b:Buffer)=>b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))||(b[0]===255&&b[1]===216&&b[2]===255)||(b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP');
export const isVideo=(b:Buffer)=>{
 if(b.length<32)return false;
 if(b.toString('ascii',4,8)==='ftyp'){
  // AVIF/HEIF also have an ftyp header. Require media data and an actual video track.
  let at=0,mdat=false,video=false;
  while(at+8<=b.length){const size=b.readUInt32BE(at);if(size<8||at+size>b.length)return false;const type=b.toString('ascii',at+4,at+8);if(type==='mdat')mdat=size>8;if(type==='moov')video=b.subarray(at+8,at+size).includes(Buffer.from('vide'));at+=size;}
  return at===b.length&&mdat&&video;
 }
 return b.subarray(0,4).equals(Buffer.from([26,69,223,163]))&&b.subarray(0,128).includes(Buffer.from('webm'))&&b.includes(Buffer.from([24,83,128,103]));
};
