const {app,BrowserWindow,WebContentsView}=require('electron');
const {spawn}=require('node:child_process');
const fs=require('node:fs');
const path=require('node:path');
app.setPath('userData',path.resolve('.runtime/spike'));
app.commandLine.appendSwitch('remote-debugging-port','9431');
app.commandLine.appendSwitch('remote-debugging-address','127.0.0.1');
async function command(args){return new Promise((resolve,reject)=>{let out='',err='';const p=spawn(path.resolve('node_modules/agent-browser/bin/agent-browser-win32-x64.exe'),['--session','honmoon-spike','--cdp','9431','--json',...args],{windowsHide:true});p.stdout.on('data',b=>out+=b);p.stderr.on('data',b=>err+=b);p.on('error',reject);p.on('exit',code=>code?reject(new Error(out+err)):resolve(JSON.parse(out)));});}
app.whenReady().then(async()=>{try{const win=new BrowserWindow({width:900,height:700,show:false});await win.loadURL('data:text/html,<h1>Shell</h1>');const view=new WebContentsView({webPreferences:{partition:'persist:spike',sandbox:true,contextIsolation:true,nodeIntegration:false}});win.contentView.addChildView(view);view.setBounds({x:0,y:100,width:900,height:600});await view.webContents.loadURL('data:text/html,<h1>HONMOON Spike</h1><label>Name<input aria-label="Name"></label><button onclick="document.querySelector(\'h1\').textContent=\'Done\'">Submit</button>');const list=await command(['tab','list']);console.log('TABS',JSON.stringify(list));const target=list.data.tabs.find(t=>t.title!=='Shell'&&t.url.includes('Spike'));console.log('TARGET',JSON.stringify(target));await command(['tab',target.targetId||target.id||target.tabId]);console.log('SNAPSHOT',JSON.stringify(await command(['snapshot','-i'])));console.log('FILL',JSON.stringify(await command(['find','role','textbox','fill','honmoon','--name','Name'])));console.log('CLICK',JSON.stringify(await command(['find','role','button','click','--name','Submit'])));console.log('RESULT',JSON.stringify(await command(['snapshot'])));fs.mkdirSync('evidence',{recursive:true});fs.writeFileSync('evidence/spike.json',JSON.stringify({list,target,result:await command(['snapshot'])},null,2));}catch(e){console.error(e);process.exitCode=1;}finally{app.quit();}});
