import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
declare global{interface Window{honmoon:{call:(method:string,args?:unknown)=>Promise<any>;subscribe:(fn:(state:any)=>void)=>()=>void}}}
const names:Record<string,string>={queued:'제어 승인 대기',running:'실행 중',awaiting_approval:'승인 대기',succeeded:'완료',failed:'실패',cancelled:'중지'};
const actionNames:Record<string,string>={click:'클릭',fill:'입력',select:'선택',check:'체크',upload:'업로드'};
function App(){
 const [s,setState]=useState<any>(null),[address,setAddress]=useState(''),[prompt,setPrompt]=useState(''),[model,setModel]=useState(''),[panel,setPanel]=useState('agent'),[agentOpen,setAgentOpen]=useState(true),[drawer,setDrawer]=useState(''),[toast,setToast]=useState(''),[working,setWorking]=useState(false),[chosen,setChosen]=useState<any>(null),[value,setValue]=useState(''),[fileId,setFileId]=useState(''),[preview,setPreview]=useState<any>(null),[vault,setVault]=useState({name:'',url:'',username:'',password:''});
 const [continuationId,setContinuationId]=useState('');const [reasoningEffort,setReasoningEffort]=useState('');
 const [taskReview,setTaskReview]=useState<any>(null),[allowUnknownCost,setAllowUnknownCost]=useState(false),[generationLimit,setGenerationLimit]=useState(1);
 const surface=useRef<HTMLDivElement>(null);const active=s?.tabs.find((t:any)=>t.id===s.activeId);const approval=s?.approvals?.[0];
 async function call(method:string,args:unknown={}){const r=await window.honmoon.call(method,args);if(!r.ok){setToast(r.error);throw new Error(r.error);}return r.data;}
 const act=(method:string,args:unknown={})=>{void call(method,args).catch(()=>{});};
 function reviewTask(){setAllowUnknownCost(false);setGenerationLimit(1);setTaskReview({taskId:s.task?.id,tabId:s.activeId,url:active.url,prompt:s.task?.prompt||prompt,files:s.files,model,reasoningEffort,continuationId});}
 async function approveTask(){const r=taskReview;const scope={tabId:r.tabId,origin:new URL(r.url).origin,fileIds:r.files.map((f:any)=>f.id),allowUnknownCost,generationLimit};try{if(r.taskId)await call('approvals.task',{taskId:r.taskId,scope});else await call('tasks.start',{prompt:r.prompt,model:r.model||undefined,reasoningEffort:r.reasoningEffort||undefined,continuationId:r.continuationId||undefined,taskApproval:scope});setTaskReview(null);}catch{}}
 useEffect(()=>{void call('state').then(setState);return window.honmoon.subscribe(setState);},[]);
 useEffect(()=>{document.documentElement.dataset.platform=s?.platform||'';},[s?.platform]);
 useEffect(()=>{document.title=s?.mediaPreview?'HONMOON · 생성 시험판':'HONMOON';},[s?.mediaPreview]);
 useEffect(()=>{if(taskReview&&(taskReview.tabId!==s?.activeId||(taskReview.taskId&&taskReview.taskId!==s?.task?.id)))setTaskReview(null);},[s?.activeId,s?.task?.id,taskReview]);
 useEffect(()=>{if(active)setAddress(active.url.endsWith('/newtab')?'':active.url);},[active?.url,s?.activeId]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{if(!s||!surface.current)return;const update=()=>{const r=surface.current!.getBoundingClientRect();act('bounds',{x:r.x,y:r.y,width:r.width,height:r.height,hidden:!!taskReview||!!drawer||!!approval||!!chosen||!!preview});};const observer=new ResizeObserver(update);observer.observe(surface.current);update();return()=>observer.disconnect();},[!!s,drawer,approval?.id,chosen,preview,panel,agentOpen,taskReview]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(taskReview)setTaskReview(null);else if(approval)act('approvals.decide',{id:approval.id,allow:false});else if(drawer||chosen||preview){setDrawer('');setChosen(null);setPreview(null);}else act('tasks.cancel');}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[approval?.id,drawer,chosen,preview,taskReview]);
 if(!s)return <div className="boot"><p>브라우저를 여는 중…</p></div>;
 async function discover(){setWorking(true);try{await call('capabilities.list');setPanel('capabilities');}catch{}finally{setWorking(false);}}
 async function invoke(){if(!chosen)return;const input=chosen.action==='upload'?{fileId}:['fill','select'].includes(chosen.action)?{value}:{};const id=chosen.id;setChosen(null);setWorking(true);try{await call('capabilities.invoke',{id,input,requestId:crypto.randomUUID()});}catch{}finally{setWorking(false);}}
 const title=(key:string)=>({history:'작업 기록',artifacts:'결과 보관함',settings:'브라우저 설정',vault:'Auth Vault',support:'사이트 지원 현황'}[key]||key);
 return <div className="app">
  <div className="main-shell"><header><div className="tabbar">{s.mediaPreview&&<span className="preview-label">생성 시험판</span>}<div className="tabs">{s.tabs.map((t:any)=><div className={'tab '+(t.id===s.activeId?'selected':'')} key={t.id}><button title={t.title} onClick={()=>act('tabs.activate',{id:t.id})}><span className="tab-icon">{t.loading?'◌':'◈'}</span>{t.title||'새 탭'}</button><button className="close-tab" aria-label={`${t.title} 닫기`} onClick={()=>act('tabs.close',{id:t.id})}>×</button></div>)}</div><button className="new-tab" aria-label="새 탭" onClick={()=>act('tabs.new')}>＋</button></div>
   <div className="addressbar"><button aria-label="뒤로" onClick={()=>act('tabs.back')}>←</button><button aria-label="앞으로" onClick={()=>act('tabs.forward')}>→</button><button aria-label="새로고침" onClick={()=>act('tabs.reload')}>↻</button><form onSubmit={e=>{e.preventDefault();act('tabs.navigate',{url:address.includes(' ')||(!address.includes('.')&&!address.includes(':'))?'https://www.google.com/search?q='+encodeURIComponent(address):address});}}><span className="address-icon">◇</span><input aria-label="웹 주소" value={address} onChange={e=>setAddress(e.target.value)} placeholder="검색어 또는 웹 주소"/></form><button className={'auth-button '+(active?.authPaused?'enabled':'')} title="인증 중에는 에이전트 관측이 중단됩니다" onClick={()=>act('auth.pause',{paused:!active?.authPaused})}>{active?.authPaused?'인증 보호 중':'로그인 모드'}</button><button className="toolbar-button" title="다운로드" aria-label="다운로드" onClick={()=>setDrawer('artifacts')}>↓</button><button className="toolbar-button" title="작업 기록" aria-label="작업 기록" onClick={()=>setDrawer('history')}>◷</button><button className={'agent-toggle '+(agentOpen?'selected':'')} aria-pressed={agentOpen} onClick={()=>setAgentOpen(!agentOpen)}>에이전트</button><button className="toolbar-button" title="설정" aria-label="설정" onClick={()=>setDrawer('settings')}>⋯</button></div>
  </header><div className="workspace"><section className="page-column">{(s.task||active?.authPaused)&&<div className="page-status"><span>{active?.authPaused?'인증 보호 중':names[s.task.status]}</span>{s.task&&<button onClick={()=>act('tasks.cancel')}>중지 · 제어권 회수</button>}</div>}<div ref={surface} className="web-surface">{!active&&<div className="empty-browser"><button className="primary" onClick={()=>act('tabs.new')}>새 탭 열기</button></div>}</div></section>
  {agentOpen&&<aside className="agent"><div className="agent-heading"><strong>에이전트</strong><button aria-label="에이전트 패널 닫기" onClick={()=>setAgentOpen(false)}>×</button></div><div className="agent-connection"><span>{s.codex.authenticated?'Codex 연결됨':s.codex.status==='ready'?'로그인 필요':s.codex.status==='connecting'?'연결 중…':'연결 안 됨'}</span><button onClick={()=>setDrawer('settings')}>{s.codex.authenticated?'설정':'연결'}</button></div><div className="switches"><button className={panel==='agent'?'active':''} onClick={()=>setPanel('agent')}>에이전트</button><button className={panel==='capabilities'?'active':''} onClick={()=>setPanel('capabilities')}>화면 기능 <small>{s.capabilities.length}</small></button><button className={panel==='log'?'active':''} onClick={()=>setPanel('log')}>실행 로그</button></div>
  <div className="agent-content">
  {panel==='agent'&&<>{s.task?<div className="task-progress"><span className="eyebrow">CURRENT TASK</span><h3>{names[s.task.status]}</h3><p>{s.task.prompt}</p><div className="progress-track"><i/></div></div>:<div className="welcome"><button className="outline" onClick={discover} disabled={working||!active}>현재 페이지 기능 찾기</button></div>}{s.mediaJobs?.slice(0,1).map((j:any)=><div className="response" key={j.id}><strong>{j.site} {j.phase==='video'?'영상':j.phase==='image'?'이미지':'생성'} · {({preparing:'준비',awaiting_approval:'승인 대기',submitted:'접수 확인 중',running:'생성 중',downloading:'다운로드 중',succeeded:'검증 완료',failed:'실패',unknown:'결과 확인 필요',cancelled:'중지'} as any)[j.status]}</strong><p>{j.error}</p>{j.artifactIds?.length>0&&<button onClick={()=>setDrawer('artifacts')}>결과 파일 {j.artifactIds.length}개</button>}</div>)}{s.codex.output&&<div className="response"><span className="eyebrow">CODEX</span><pre>{s.codex.output}</pre></div>}{!s.task&&s.tasks[0]?.error&&<div className="task-error">최근 작업: {names[s.tasks[0].status]}<p>{s.tasks[0].error}</p></div>}</>}
  {panel==='capabilities'&&<><div className="cap-heading"><span>현재 화면에서 발견한 기능</span><button disabled={working||!!s.task} onClick={discover}>↻ 다시 찾기</button></div><p className="hint">후보 발견은 실행 허가가 아닙니다. 기능을 눌러 입력과 대상을 확인하고 승인하세요.</p>{s.capabilities.filter((c:any)=>c.tabId===s.activeId).map((c:any)=><button className="capability" key={c.id} disabled={!!s.task||working} onClick={()=>{setChosen(c);setValue('');setFileId(s.files[0]?.id||'');}}><span className="cap-type">{actionNames[c.action]}</span><strong>{c.name}</strong><small>{c.reviewed?'검토됨':'미검토'} →</small></button>)}{!s.capabilities.length&&<div className="empty">기능 찾기를 눌러 현재 페이지를 조사하세요.</div>}</>}
  {panel==='log'&&<div className="logs">{s.events.map((event:any,i:number)=><div key={i}><time>{new Date(event.at).toLocaleTimeString()}</time><strong>{event.kind}</strong><pre>{JSON.stringify(event.body,null,2)}</pre></div>)}</div>}
  </div><div className="composer"><label htmlFor="task-prompt">작업</label><textarea id="task-prompt" value={prompt} disabled={!!s.task} onChange={e=>setPrompt(e.target.value)} placeholder="이 페이지에서 할 작업을 입력하세요."/><div className="composer-tools"><button onClick={()=>act('files.pick')}>＋ 파일 <span>{s.files.length||''}</span></button><select aria-label="Codex 모델" value={model} onChange={e=>setModel(e.target.value)}><option value="">사이트 기본값 · 생성: Luna high</option>{s.codex.models.map((m:any)=><option key={m.id} value={m.model}>{m.name}</option>)}</select><select aria-label="추론 강도" value={reasoningEffort} onChange={e=>setReasoningEffort(e.target.value)}><option value="">기본 추론 · 생성: high</option><option value="low">low</option><option value="medium">medium</option><option value="high">high</option></select></div><label>이전 결과 이어가기<select aria-label="이전 결과 이어가기" value={continuationId} disabled={!!s.task} onChange={e=>setContinuationId(e.target.value)}><option value="">새 작업 · 이전 문맥 없음</option>{s.tasks.filter((t:any)=>['succeeded','failed','cancelled'].includes(t.status)).slice(0,20).map((t:any)=><option key={t.id} value={t.id}>{t.prompt.slice(0,50)}</option>)}</select></label><button className="outline task-approve" disabled={!!s.task||!prompt.trim()||!active||!s.codex.authenticated} onClick={reviewTask}>작업 전체 승인 후 시작</button><button className="primary run" disabled={!!s.task||!prompt.trim()||!active||!s.codex.authenticated} onClick={()=>act('tasks.start',{prompt,model:model||undefined,reasoningEffort:reasoningEffort||undefined,continuationId:continuationId||undefined})}>작업 시작 <span>↗</span></button>{s.task&&!s.taskApproval&&<button className="outline task-approve" onClick={reviewTask}>이 작업 전체 승인</button>}{s.taskApproval&&<p className="task-approval-status">전체 승인 적용 · 생성 {s.taskApproval.generationsUsed}/{s.taskApproval.generationLimit}회 · 중지하면 해제</p>}<button className="stop" disabled={!s.task} onClick={()=>act('tasks.cancel')}>■ 긴급 중지 <span>ESC</span></button></div></aside>}</div></div>
  {(taskReview||drawer||chosen||preview||approval)&&<div className="modal-backdrop"><section className={'modal '+(drawer?'wide':'')} role="dialog" aria-modal="true" aria-label={taskReview?'작업 전체 승인':approval?'실행 승인':chosen?'기능 실행':title(drawer)}><div className="modal-top"><span className="eyebrow">{taskReview?'작업 전체 승인':approval?'실행 확인':title(drawer)}</span>{!approval&&<button aria-label="닫기" onClick={()=>{setDrawer('');setChosen(null);setPreview(null);}}>×</button>}</div>
   {taskReview?<><h2>이 작업 전체 승인</h2><p className="hint">아래 작업에 한해 에이전트가 선택한 입력·선택·클릭·파일 전송·결과 조회와 복구 관측을 반복 확인 없이 실행합니다. 로그인·웹사이트 권한은 포함하지 않습니다.</p><p><strong>사이트</strong> {new URL(taskReview.url).origin}</p><pre className="approval-detail">{taskReview.prompt}</pre><p>전송 가능한 파일: {taskReview.files.map((f:any)=>f.name).join(', ')||'없음'}</p><label>최대 생성 제출 횟수 <input aria-label="전체 승인 생성 횟수" type="number" min="1" max="10" value={generationLimit} onChange={e=>setGenerationLimit(Number(e.target.value))}/></label><p className="hint">이미지 생성 후 영상 변환은 제출 2회가 필요합니다. Grok 영상 기본값은 480p입니다. 생성 모델·옵션은 작업 지시를 따르며, 미지정 값은 사이트 현재 설정을 사용합니다. 유료 생성·사이트 클릭의 효과도 포함됩니다. 실제 비용 상한을 보장하지 않습니다.</p><label className="task-cost-consent"><input type="checkbox" checked={allowUnknownCost} onChange={e=>setAllowUnknownCost(e.target.checked)}/> 비용 표시를 확인할 수 없어도 이 작업의 생성을 허용</label><p className="hint">현재 탭과 선택 파일에만 적용됩니다. 중지·탭 전환·임대 만료·앱 종료 시 해제되며 새 작업에는 적용되지 않습니다. 성공 여부는 별도로 검증합니다.</p><div className="modal-actions"><button className="outline" onClick={()=>setTaskReview(null)}>취소</button><button className="primary" disabled={!Number.isInteger(generationLimit)||generationLimit<1||generationLimit>10} onClick={()=>void approveTask()}>{taskReview.taskId?'이 작업 전체 승인':'전체 승인하고 시작'}</button></div></>:approval?<><h2>{approval.title}</h2>{s.task&&!s.taskApproval&&approval.taskId===s.task.id&&<button className="outline task-approve" onClick={reviewTask}>이 작업 전체 승인</button>}<pre className="approval-detail">{approval.detail}</pre><p className="hint">승인은 2분 후 만료됩니다. 중지하거나 화면이 바뀌면 다시 확인합니다.</p><div className="modal-actions"><button className="outline" onClick={()=>act('approvals.decide',{id:approval.id,allow:false})}>거절</button><button className="primary" onClick={()=>act('approvals.decide',{id:approval.id,allow:true})}>{approval.kind==='result'?'결과 확인 · 완료':approval.kind==='read'||approval.kind==='recovery'?'1회 전달 승인':'1회 승인하고 실행 ↗'}</button></div></>:chosen?<><h2>{chosen.name}</h2><p className="hint">{actionNames[chosen.action]} · {chosen.origin}</p>{['fill','select'].includes(chosen.action)&&<textarea aria-label="실행 입력값" value={value} onChange={e=>setValue(e.target.value)} placeholder="입력할 내용을 적으세요"/>}{chosen.action==='upload'&&<><select aria-label="업로드 파일" value={fileId} onChange={e=>setFileId(e.target.value)}><option value="">파일 선택</option>{s.files.map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button className="outline" onClick={()=>act('files.pick')}>파일 추가</button></>}<div className="modal-actions"><button className="primary" onClick={invoke}>실행 검토 요청 ↗</button></div></>:preview?<><h2>결과 미리보기</h2>{preview.mime.startsWith('image')?<img className="artifact-preview" src={`data:${preview.mime};base64,${preview.data}`}/>:<video className="artifact-preview" controls src={`data:${preview.mime};base64,${preview.data}`}/>}</>:<><h2>{title(drawer)}</h2>
   {drawer==='history'&&(s.tasks.length?s.tasks.map((t:any)=><article className="record" key={t.id}><span className={'state-badge '+t.status}>{names[t.status]}</span><strong>{t.prompt}</strong><small>{new Date(t.createdAt).toLocaleString()} · {t.origin}</small>{t.error&&<p>{t.error}</p>}{t.usage&&<small>입력 {t.usage.inputTokens.toLocaleString()} 토큰 · 캐시 {t.usage.cachedInputTokens.toLocaleString()} · 출력 {t.usage.outputTokens.toLocaleString()}</small>}{t.output&&<pre>{t.output}</pre>}</article>):<p className="empty">아직 실행한 작업이 없습니다.</p>)}
   {drawer==='artifacts'&&(s.artifacts.length?s.artifacts.map((a:any)=><article className="record" key={a.id}><strong>{a.name}</strong><small>{a.status} · {(a.bytes/1024).toFixed(1)} KB · {new Date(a.createdAt).toLocaleString()}</small><small>{a.sourceUrl}</small><div className="record-actions"><button className="outline" onClick={()=>act('artifacts.reveal',{id:a.id})}>폴더에서 보기</button>{/^(image\/(png|jpeg|webp|gif)|video\/(mp4|webm))$/.test(a.mime)&&<button className="outline" onClick={()=>void call('artifacts.preview',{id:a.id}).then(setPreview).catch(()=>{})}>미리보기</button>}</div></article>):<p className="empty">실제 웹사이트에서 다운로드한 파일이 이곳에 표시됩니다.</p>)}
   {drawer==='settings'&&<><div className="record-actions"><button className="outline" onClick={()=>setDrawer('vault')}>인증 보관함</button><button className="outline" onClick={()=>setDrawer('support')}>사이트 지원</button></div><section className="settings-section"><h3>Codex 연결</h3><div className="record-actions"><button className="outline" onClick={()=>act('codex.connect')}>연결 다시 시도</button><button className="outline" onClick={()=>act('codex.binary')}>실행파일 위치 지정</button></div><p className="runtime-path">{s.runtimes?.codex.path||'Codex CLI 위치 확인 필요'}</p><p>{s.codex.authenticated?'HONMOON용 Codex 인증이 연결되었습니다.':'기존 Codex 설정과 분리된 HONMOON 전용 계정 저장소를 사용합니다.'}</p><button className="primary" onClick={()=>act('codex.login')}>ChatGPT 계정으로 연결 ↗</button>{s.codex.login&&<div className="login-code"><strong>{s.codex.login.userCode}</strong><p>열린 인증 탭에서 위 코드를 입력하세요. 로그인 후 탭의 ‘인증 보호 중’을 해제합니다.</p></div>}</section><section className="settings-section"><h3>작업 실행 방식</h3><select aria-label="작업 실행 방식" value={s.executionMode||'legacy'} disabled={!!s.task} onChange={e=>act('settings.execution',{mode:e.target.value})}><option value="legacy">기존 기능 호출</option><option value="compact">작업 묶음 · 실험 기능</option></select><p>작업 묶음은 입력·선택·결과 확인을 브라우저에서 이어서 수행합니다.</p></section><section className="settings-section"><h3>외부 에이전트 MCP</h3><p>HONMOON이 실행 중일 때 로컬 MCP로 연결합니다. 작업 제어는 이 앱의 승인을 받습니다. 배포본은 자체 런타임으로 연결됩니다.</p><div className="record-actions">{(['codex','claude','antigravity'] as const).map(client=><button key={client} className="outline" onClick={()=>{act('mcp.copy',{client});setToast(client+' 연결 설정을 복사했습니다.');}}>{({codex:'Codex TOML',claude:'Claude JSON',antigravity:'Antigravity JSON'})[client]}</button>)}</div></section><section className="settings-section"><h3>실제 브라우저 검사</h3><p>로컬 테스트 사이트에서 로그인·입력·파일 전송·다운로드를 확인할 수 있습니다. 실제 AI 생성 서비스가 아닙니다.</p><button className="outline" onClick={()=>{act('tabs.new',{url:s.fixtureUrl});setDrawer('');}}>테스트 사이트 열기</button></section><p className="hint">Electron {s.versions.electron} / Chromium {s.versions.chromium}<br/>agent-browser {s.versions.agentBrowser} · 전용 영속 프로필</p></>}
   {drawer==='support'&&s.support.map((site:any)=><article className="record" key={site.id}><strong>{site.name}</strong><span className="state-badge">{site.state==='available'?'사용 가능':'실계정 검증 필요'}</span><p>{site.detail}</p></article>)}
   {drawer==='vault'&&<><p className="hint">사용자가 직접 저장·실행하는 인증 보관함입니다. 비밀번호는 모델에 전달하지 않습니다. 키는 운영체제 보호 저장소(macOS Keychain / Windows DPAPI)로 관리합니다.</p>{s.vaults.map((v:any)=><article className="record" key={v.id}><strong>{v.name}</strong><small>{v.url}</small><button className="outline" onClick={()=>act('vault.login',{id:v.id})}>현재 탭에서 로그인</button></article>)}<form onSubmit={async e=>{e.preventDefault();try{await call('vault.save',vault);setVault({name:'',url:'',username:'',password:''});setToast('인증정보를 암호화해 저장했습니다.');}catch{}}}><div className="vault-grid">{(['name','url','username','password'] as const).map((key,i)=><label key={key}>{['항목 이름','로그인 URL','사용자 이름','비밀번호'][i]}<input required type={key==='password'?'password':'text'} autoComplete="off" value={vault[key]} onChange={e=>setVault({...vault,[key]:e.target.value})}/></label>)}</div><button className="primary" type="submit">암호화하여 저장</button></form></>}
   </>}
  </section></div>}
  {(toast||s.error)&&<div className="toast" role="status"><span>{toast||s.error}</span><button aria-label="알림 닫기" onClick={()=>{setToast('');act('error.clear');}}>×</button></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
